-- WARNING: This will DELETE all existing data in these tables.
-- Run with: psql "$DATABASE_URL" -f reset_and_seed.sql

-- Use DMV (DC/MD/VA) timezone so NOW() and defaults are Eastern
SET timezone = 'America/New_York';

BEGIN;

-- =========================
-- Drop existing tables
-- =========================
DROP TABLE IF EXISTS booking_items CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS packages CASCADE;
DROP TABLE IF EXISTS services CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS contact_messages CASCADE;
DROP TABLE IF EXISTS blog_posts CASCADE;
DROP TABLE IF EXISTS business_info CASCADE;
DROP TABLE IF EXISTS available_slots CASCADE;
DROP TABLE IF EXISTS faqs CASCADE;

-- =========================
-- Create tables (Postgres)
-- Schema: availability (available_slots), bookings with duration_minutes +
-- completed_at + location, booking_items for multi-package, packages tiered
-- pricing + turnaround_hours. Matches app models for full DB rerun.
-- =========================

CREATE TABLE customers (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL UNIQUE,
    phone       VARCHAR(20),
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX ix_customers_id ON customers (id);
CREATE INDEX ix_customers_email ON customers (email);

CREATE TABLE services (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    slug        VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    image_url   VARCHAR(500),
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX ix_services_id ON services (id);

CREATE TABLE packages (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id             INTEGER NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    name                   VARCHAR(255) NOT NULL,
    description            TEXT,
    price                  DOUBLE PRECISION,
    price_small            DOUBLE PRECISION,
    price_medium           DOUBLE PRECISION,
    price_large            DOUBLE PRECISION,
    price_original_small   DOUBLE PRECISION,
    price_original_medium  DOUBLE PRECISION,
    price_original_large   DOUBLE PRECISION,
    duration_minutes       INTEGER,
    turnaround_hours       INTEGER,
    details                TEXT,
    image_url              VARCHAR(500),
    display_order          INTEGER DEFAULT 0,
    created_at             TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX ix_packages_id ON packages (id);

CREATE TABLE available_slots (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_start TIMESTAMPTZ NOT NULL,
    slot_end   TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX ix_available_slots_id ON available_slots (id);

CREATE TABLE bookings (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id       INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    package_id        INTEGER REFERENCES packages(id) ON DELETE SET NULL,
    available_slot_id INTEGER REFERENCES available_slots(id) ON DELETE SET NULL,
    scheduled_date    TIMESTAMPTZ NOT NULL,
    duration_minutes  INTEGER,
    status            VARCHAR(50) DEFAULT 'pending',
    completed_at      TIMESTAMPTZ,
    location          VARCHAR(500),
    notes             TEXT,
    created_at        TIMESTAMPTZ DEFAULT NOW(),
    updated_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX ix_bookings_id ON bookings (id);

CREATE TABLE booking_items (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INTEGER NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    package_id INTEGER NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
    quantity   INTEGER DEFAULT 1
);

CREATE INDEX ix_booking_items_id ON booking_items (id);

CREATE TABLE reviews (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    rating      INTEGER NOT NULL,
    comment     TEXT NOT NULL,
    service_id  INTEGER REFERENCES services(id) ON DELETE SET NULL,
    verified    BOOLEAN DEFAULT FALSE,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX ix_reviews_id ON reviews (id);

CREATE TABLE contact_messages (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    phone      VARCHAR(20),
    message    TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX ix_contact_messages_id ON contact_messages (id);

CREATE TABLE blog_posts (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(500) NOT NULL,
    slug        VARCHAR(500) NOT NULL UNIQUE,
    content     TEXT NOT NULL,
    image_url   VARCHAR(500),
    published   BOOLEAN DEFAULT FALSE,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX ix_blog_posts_id ON blog_posts (id);

CREATE TABLE business_info (
    id                          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone                       VARCHAR(20),
    email                       VARCHAR(255),
    address                     VARCHAR(500),
    city                        VARCHAR(100),
    state                       VARCHAR(50),
    zip_code                    VARCHAR(10),
    service_areas               TEXT,
    business_hours_monday_open  VARCHAR(10),
    business_hours_monday_close VARCHAR(10),
    business_hours_sunday_open  VARCHAR(10),
    business_hours_sunday_close VARCHAR(10)
);

CREATE INDEX ix_business_info_id ON business_info (id);

CREATE TABLE faqs (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question    VARCHAR(500) NOT NULL,
    answer      TEXT NOT NULL,
    order_index INTEGER,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX ix_faqs_id ON faqs (id);

-- =========================
-- Seed core services
-- =========================

INSERT INTO services (name, slug, description)
VALUES
    ('Full Detailing',       'full-detailing',       'Interior and exterior detailing. Choose your level.'),
    ('Interior Detailing',   'interior-detailing',   'Deep clean and condition your vehicle interior. Choose your level.'),
    ('Exterior Detailing',   'exterior-detailing',   'Wash, polish, and protect exterior surfaces. Choose your level.'),
    ('Ceramic Coating',      'ceramic-coating',      'Protective ceramic coating for your vehicle''s paint.'),
    ('Paint Correction',     'paint-correction',     'Professional paint correction to restore your vehicle''s finish.'),
    ('Monthly Maintenance',  'monthly-maintenance',  'Regular maintenance plans to keep your vehicle looking its best.'),
    ('Fleet Detailing',      'fleet-detailing',      'Wash and wax options for fleet vehicles. Pricing per foot.')
ON CONFLICT (slug) DO NOTHING;

-- =========================
-- Seed packages (mirrors app.seed)
-- =========================

WITH svc AS (
    SELECT id, slug FROM services
)
INSERT INTO packages (
    service_id, display_order, name, description, duration_minutes,
    price, price_small, price_medium, price_large,
    price_original_small, price_original_medium, price_original_large,
    turnaround_hours, details
)
-- Full Detailing (no booking after 1PM)
SELECT s.id, 0,
       'Level 1',
       'Essential interior and exterior detail.',
       300,
       248, 248, 293, 338,
       275, 325, 375,
       5,
       'Vacuum floors and trunk
Wipe down vinyl/plastic and mats
Vacuum cloth seats
Wipe leather seats
Clean console and cup holders
Clean dash with UV protect
Clean interior trim and plastics
Clean door panels and pockets
Clean door jambs
Clean all glass
Two-bucket hand wash
Hand wash wheels and tires
Decontaminate paint
Trim dressing
No-sling tire dressing
Paint sealant (wax)'
FROM svc s WHERE s.slug = 'full-detailing'
UNION ALL
SELECT s.id, 1,
       'Level 2',
       'Everything in Level 1 plus deeper cleaning and protection.',
       360,
       293, 293, 338, 383,
       325, 375, 425,
       6,
       'Everything from our Level 1 Package plus:
Clean vehicle headliner
Shampoo cloth floor mats
Shampoo carpeting in cabin and trunk
Shampoo cloth seats
Decontaminate with clay bar
Pet hair and sand removal if present
Paint sealant for 3-month protection'
FROM svc s WHERE s.slug = 'full-detailing'
UNION ALL
SELECT s.id, 2,
       'Level 3',
       'Everything from Level 1 and Level 2. For vehicles that are extremely dirty inside and out.',
       420,
       473, 473, 518, 563,
       525, 575, 625,
       7,
       'Everything from Level 1 and Level 2.
For vehicles extremely dirty inside and out:
Excessive staining
Pet hair and sand
Throw-up or long-term neglect'
FROM svc s WHERE s.slug = 'full-detailing'

UNION ALL
-- Interior Detailing (no booking after 4PM)
SELECT s.id, 0,
       'Level 1',
       'Essential interior clean and protect.',
       150,
       149, 149, 179, 209,
       165, 199, 229,
       2,
       'Vacuum and wipe all surfaces
Clean console and dash
Clean door panels and jambs
Glass cleaning'
FROM svc s WHERE s.slug = 'interior-detailing'
UNION ALL
SELECT s.id, 1,
       'Level 2',
       'Deeper interior detail with conditioning.',
       180,
       219, 219, 259, 299,
       245, 289, 329,
       3,
       'Everything in Level 1 plus:
Shampoo carpets and mats
Leather conditioning
Headliner cleaning'
FROM svc s WHERE s.slug = 'interior-detailing'
UNION ALL
SELECT s.id, 2,
       'Level 3',
       'Full interior detail for heavily soiled vehicles.',
       240,
       349, 349, 399, 449,
       385, 439, 495,
       4,
       'Everything in Level 1 and 2 plus:
Deep stain removal
Pet hair removal
Full interior sanitization'
FROM svc s WHERE s.slug = 'interior-detailing'

UNION ALL
-- Exterior Detailing (no booking after 4PM)
SELECT s.id, 0,
       'Level 1',
       'Wash, wax, and basic exterior care.',
       120,
       99, 99, 129, 159,
       109, 144, 179,
       2,
       'Two-bucket hand wash
Wheels and tires
Basic wax application'
FROM svc s WHERE s.slug = 'exterior-detailing'
UNION ALL
SELECT s.id, 1,
       'Level 2',
       'Clay, polish, and sealant.',
       150,
       179, 179, 219, 259,
       199, 243, 289,
       3,
       'Everything in Level 1 plus:
Paint decontamination (clay)
Polish
Sealant'
FROM svc s WHERE s.slug = 'exterior-detailing'
UNION ALL
SELECT s.id, 2,
       'Level 3',
       'Full exterior correction and protection.',
       180,
       279, 279, 329, 379,
       309, 365, 419,
       3,
       'Everything in Level 1 and 2 plus:
Paint correction
Premium sealant or coating prep'
FROM svc s WHERE s.slug = 'exterior-detailing'

UNION ALL
-- Ceramic Coating (no booking after 10AM)
SELECT s.id, 0,
       '1 Year Ceramic Coating',
       'One-year ceramic coating protection.',
       240,
       299, 299, 349, 399,
       329, 384, 439,
       4,
       'Paint preparation
Ceramic coating application
Curing time'
FROM svc s WHERE s.slug = 'ceramic-coating'
UNION ALL
SELECT s.id, 1,
       '3 Year Ceramic Coating',
       'Three-year ceramic coating protection.',
       420,
       499, 499, 574, 649,
       549, 629, 714,
       7,
       'Full decontamination
Paint correction (as needed)
3-year ceramic coating'
FROM svc s WHERE s.slug = 'ceramic-coating'
UNION ALL
SELECT s.id, 2,
       '5 Year Ceramic Coating',
       'Five-year ceramic coating protection.',
       600,
       699, 699, 799, 899,
       769, 879, 989,
       10,
       'Full prep and correction
5-year ceramic coating
Multiple layers'
FROM svc s WHERE s.slug = 'ceramic-coating'

UNION ALL
-- Paint Correction (no booking after 10AM)
SELECT s.id, 0,
       '1 Step paint correction',
       '1 step paint correction.',
       420,
       500, 500, 600, 700,
       500, 600, 700,
       7,
       'Pre-wash and hand wash
Wheels and tires
Paint correction'
FROM svc s WHERE s.slug = 'paint-correction'
UNION ALL
SELECT s.id, 1,
       '2 Step paint correction',
       '2 step paint correction.',
       600,
       1000, 1000, 1200, 1300,
       1000, 1200, 1300,
       10,
       'Pre-wash and hand wash
Wheels and tires
2 step correction'
FROM svc s WHERE s.slug = 'paint-correction'

UNION ALL
-- Monthly Maintenance (no booking after 4PM; Biweekly hidden in UI for now)
SELECT s.id, 0,
       'Biweekly',
       'Maintenance wash and interior tidy every two weeks.',
       45,
       79, 79, 99, 119,
       87, 109, 131,
       1,
       'Exterior wash
Interior vacuum and wipe
Quick detail'
FROM svc s WHERE s.slug = 'monthly-maintenance'
UNION ALL
SELECT s.id, 1,
       'Monthly',
       'Monthly maintenance detail to keep your vehicle in top shape.',
       180,
       129, 129, 159, 189,
       142, 175, 208,
       3,
       'Full maintenance wash
Interior deep tidy
Tire and trim dressing'
FROM svc s WHERE s.slug = 'monthly-maintenance'

UNION ALL
-- Fleet Detailing
SELECT s.id, 0,
       'Wash & Spray Wax',
       'Wash and spray wax. Pricing per foot.',
       60,
       15, 15, 15, 15,
       15, 15, 15,
       1,
       'Wash and spray wax'
FROM svc s WHERE s.slug = 'fleet-detailing'
UNION ALL
SELECT s.id, 1,
       'Wash & Hand Wax',
       'Wash and hand wax. Pricing per foot.',
       120,
       35, 35, 35, 35,
       35, 35, 35,
       2,
       'Wash and hand wax'
FROM svc s WHERE s.slug = 'fleet-detailing';

COMMIT;
