-- WARNING: This will DELETE all existing data in these tables.
-- Run with: psql "$DATABASE_URL" -f reset_and_seed.sql

-- Use DMV (DC/MD/VA) timezone so NOW() and defaults are Eastern
SET timezone = 'America/New_York';

BEGIN;

-- =========================
-- Drop existing tables
-- =========================
DROP TABLE IF EXISTS booking_items CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS packages CASCADE;
DROP TABLE IF EXISTS services CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS contact_messages CASCADE;
DROP TABLE IF EXISTS blog_posts CASCADE;
DROP TABLE IF EXISTS business_info CASCADE;
DROP TABLE IF EXISTS available_slots CASCADE;
DROP TABLE IF EXISTS faqs CASCADE;

-- =========================
-- Create tables (Postgres)
-- Schema: availability (available_slots), bookings with duration_minutes +
-- completed_at + location, booking_items for multi-package, packages tiered
-- pricing + turnaround_hours. Matches app models for full DB rerun.
-- =========================

CREATE TABLE customers (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL UNIQUE,
    phone       VARCHAR(20),
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX ix_customers_id ON customers (id);
CREATE INDEX ix_customers_email ON customers (email);

CREATE TABLE services (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    slug        VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    image_url   VARCHAR(500),
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX ix_services_id ON services (id);

CREATE TABLE packages (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id             INTEGER NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    name                   VARCHAR(255) NOT NULL,
    description            TEXT,
    price                  DOUBLE PRECISION,
    price_small            DOUBLE PRECISION,
    price_medium           DOUBLE PRECISION,
    price_large            DOUBLE PRECISION,
    price_original_small   DOUBLE PRECISION,
    price_original_medium  DOUBLE PRECISION,
    price_original_large   DOUBLE PRECISION,
    duration_minutes       INTEGER,
    turnaround_hours       INTEGER,
    details                TEXT,
    image_url              VARCHAR(500),
    display_order          INTEGER DEFAULT 0,
    created_at             TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX ix_packages_id ON packages (id);

CREATE TABLE available_slots (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_start TIMESTAMPTZ NOT NULL,
    slot_end   TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX ix_available_slots_id ON available_slots (id);

CREATE TABLE bookings (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id       INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    package_id        INTEGER REFERENCES packages(id) ON DELETE SET NULL,
    available_slot_id INTEGER REFERENCES available_slots(id) ON DELETE SET NULL,
    scheduled_date    TIMESTAMPTZ NOT NULL,
    duration_minutes  INTEGER,
    status            VARCHAR(50) DEFAULT 'pending',
    completed_at      TIMESTAMPTZ,
    location          VARCHAR(500),
    notes             TEXT,
    created_at        TIMESTAMPTZ DEFAULT NOW(),
    updated_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX ix_bookings_id ON bookings (id);

CREATE TABLE booking_items (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INTEGER NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    package_id INTEGER NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
    quantity   INTEGER DEFAULT 1
);

CREATE INDEX ix_booking_items_id ON booking_items (id);

CREATE TABLE reviews (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    rating      INTEGER NOT NULL,
    comment     TEXT NOT NULL,
    service_id  INTEGER REFERENCES services(id) ON DELETE SET NULL,
    verified    BOOLEAN DEFAULT FALSE,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX ix_reviews_id ON reviews (id);

CREATE TABLE contact_messages (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    phone      VARCHAR(20),
    message    TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX ix_contact_messages_id ON contact_messages (id);

CREATE TABLE blog_posts (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(500) NOT NULL,
    slug        VARCHAR(500) NOT NULL UNIQUE,
    content     TEXT NOT NULL,
    image_url   VARCHAR(500),
    published   BOOLEAN DEFAULT FALSE,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX ix_blog_posts_id ON blog_posts (id);

CREATE TABLE business_info (
    id                          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone                       VARCHAR(20),
    email                       VARCHAR(255),
    address                     VARCHAR(500),
    city                        VARCHAR(100),
    state                       VARCHAR(50),
    zip_code                    VARCHAR(10),
    service_areas               TEXT,
    business_hours_monday_open  VARCHAR(10),
    business_hours_monday_close VARCHAR(10),
    business_hours_sunday_open  VARCHAR(10),
    business_hours_sunday_close VARCHAR(10)
);

CREATE INDEX ix_business_info_id ON business_info (id);

CREATE TABLE faqs (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question    VARCHAR(500) NOT NULL,
    answer      TEXT NOT NULL,
    order_index INTEGER,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX ix_faqs_id ON faqs (id);

-- =========================
-- Seed core services
-- =========================

INSERT INTO services (name, slug, description)
VALUES
    ('Full Detailing',       'full-detailing',       'Interior and exterior detailing. Choose your level.'),
    ('Interior Detailing',   'interior-detailing',   'Deep clean and condition your vehicle interior. Choose your level.'),
    ('Exterior Detailing',   'exterior-detailing',   'Wash, polish, and protect exterior surfaces. Choose your level.'),
    ('Ceramic Coating',      'ceramic-coating',      'Protective ceramic coating for your vehicle''s paint.'),
    ('Paint Correction',     'paint-correction',     'Professional paint correction to restore your vehicle''s finish.'),
    ('Monthly Maintenance',  'monthly-maintenance',  'Regular maintenance plans to keep your vehicle looking its best.'),
    ('Fleet Detailing',      'fleet-detailing',      'Wash and wax options for fleet vehicles. Pricing per foot.')
ON CONFLICT (slug) DO NOTHING;

-- =========================
-- Seed packages (mirrors app.seed)
-- =========================

WITH svc AS (
    SELECT id, slug FROM services
)
INSERT INTO packages (
    service_id, display_order, name, description, duration_minutes,
    price, price_small, price_medium, price_large,
    price_original_small, price_original_medium, price_original_large,
    turnaround_hours, details
)
-- Full Detailing (no booking after 1PM) — prices/copy aligned with frontend ServicePage.jsx
SELECT s.id, 0,
       'Level 1',
       'Full detailing',
       270,
       280, 280, 320, 370,
       NULL, NULL, NULL,
       5,
       'Interior items
Complete vacuum of floor and trunks area
Wash vinyl or rubber floor mats
Vacuum cloth seats
Wipe down leather seats
Shampoo floor mats and carpets
Deep clean and condition leather seat
Clean dashboard and apply UV protection
Full wipe-down of all plastics and interior trim
Cleaning of center console, vents, cup holders, and tight areas
Door panels and door storage pockets cleaned and conditioned
Door jambs cleaned
Windows and mirrors cleaned streak-free
Exterior Items
Your vehicle will receive a careful hand wash and protective finish for a clean, glossy look.
Gentle pre-rinse using spot-free water
Complete hand wash using spot-free water
Wheels, tires, and wheel wells cleaned by hand
Gas cap area cleaned
Tire dressing applied
Paint sealant applied for shine and protection'
FROM svc s WHERE s.slug = 'full-detailing'
UNION ALL
SELECT s.id, 1,
       'Level 2',
       'Deep Full Detailing Upgrade',
       330,
       330, 330, 370, 390,
       NULL, NULL, NULL,
       6,
       'What''s Included
Includes everything in our Level 1 Detail, plus the following advanced services:
Full shampoo extraction of cloth seats
Steam treatment of cloth seats to sanitize and break down stains
Deep shampoo and steam treatment of carpets in cabin and trunk
Remove bug splatters from surfaces
Remove environmental fallout with detailers clay from paint
Chemically remove tar overspray and road grime
Pet hair and sand removal (if present)'
FROM svc s WHERE s.slug = 'full-detailing'
UNION ALL
SELECT s.id, 2,
       'Level 3',
       'Extreme Restoration',
       390,
       470, 470, 520, 560,
       NULL, NULL, NULL,
       7,
       'Who This Package Is For
This service is designed for vehicles in heavy or neglected condition that require extensive cleaning and extra labor.
What''s Included
Includes everything in Level 1 and Level 2, plus:
Intensive stain treatment and extraction
Extended pet hair removal process
Deep interior cleaning
Heavy exterior decontamination
Extra labor time for severely soiled areas
Important Notice: Final pricing is determined after in-person inspection. Vehicles with biohazard material (excessive bodily fluids, mold, etc.) may require specialized treatment and additional charges.'
FROM svc s WHERE s.slug = 'full-detailing'

UNION ALL
-- Interior Detailing (no booking after 4PM)
SELECT s.id, 0,
       'Level 1',
       'Interior Detailing',
       150,
       200, 200, 220, 250,
       NULL, NULL, NULL,
       3,
       'Interior items
Complete vacuum of floor and trunks area
Wash vinyl or rubber floor mats
Vacuum cloth seats
Wipe down leather seats
Shampoo treatment of cloth floor mats
Deep clean and condition leather seat
Clean dashboard and apply UV protection
Full wipe-down of all plastics and interior trim
Cleaning of center console, vents, cup holders, and tight areas
Door panels and door storage pockets cleaned and conditioned
Door jambs cleaned
Interior windows and mirrors cleaned streak-free'
FROM svc s WHERE s.slug = 'interior-detailing'
UNION ALL
SELECT s.id, 1,
       'Level 2',
       'Deep interior upgrade',
       165,
       250, 250, 270, 290,
       NULL, NULL, NULL,
       3,
       'Includes everything in our Level 1 Detail, plus the following advanced services:
Deep shampoo extraction of cloth seats
Steam treatment of cloth seats to sanitize and break down stains
Deep shampoo and steam treatment of carpets in cabin and trunk
Pet hair and sand removal (if present)'
FROM svc s WHERE s.slug = 'interior-detailing'
UNION ALL
SELECT s.id, 2,
       'Level 3',
       'Extreme Restoration',
       225,
       330, 330, 350, 390,
       NULL, NULL, NULL,
       4,
       'This service is designed for vehicles in heavy soiled interior. This package includes extended labor time, extra extraction, and detailed restoration.'
FROM svc s WHERE s.slug = 'interior-detailing'

UNION ALL
-- Exterior Detailing (no booking after 4PM)
SELECT s.id, 0,
       'Level 1',
       'Wash, Wax & Interior wipe down',
       90,
       140, 140, 160, 180,
       NULL, NULL, NULL,
       2,
       'Gentle pre-rinse using spot-free water
Complete hand wash using spot-free water
Wheels, tires, and wheel wells cleaned by hand
Gas cap area cleaned
Tire dressing applied
Paint sealant applied for shine and protection
Vacuum and wipe down vinyl or plastic floor mats
Vacuum cloth seat
Wipe down dashboard'
FROM svc s WHERE s.slug = 'exterior-detailing'
UNION ALL
SELECT s.id, 1,
       'Level 2',
       'Deep Detailing Upgrade',
       150,
       190, 190, 210, 230,
       NULL, NULL, NULL,
       3,
       'Includes everything in our Level 1 Detail, plus the following advanced services:
Deep shampoo of carpets in cabin and trunk
Remove bug splatters from surfaces
Remove environmental fallout with detailers clay from paint
Chemically remove tar overspray and road grime
Pet hair and sand removal (if present)
UV protection applied to dashboard and panels'
FROM svc s WHERE s.slug = 'exterior-detailing'
UNION ALL
SELECT s.id, 2,
       'Level 3',
       'Extreme Restoration',
       165,
       280, 280, 310, 330,
       NULL, NULL, NULL,
       3,
       'For vehicles with heavy grime, brake dust, or long-term neglect. Add-On Service: Engine bay cleaning and dressing: $85'
FROM svc s WHERE s.slug = 'exterior-detailing'

UNION ALL
-- Ceramic Coating (no booking after 10AM)
SELECT s.id, 0,
       '1 Year Ceramic Coating',
       '1 Year ceramic coating',
       240,
       440, 440, 490, 540,
       NULL, NULL, NULL,
       4,
       'Benefits of Ceramic Coating:
Protects your vehicle''s paint from UV damage and oxidation
Maintains long-term paint condition and resale value
Creates a hydrophobic barrier that repels water & contaminants
Enhances gloss, depth, and color clarity for a rich, polished finish
Reduces maintenance time & makes cleaning effortless
Pre-wash and 100% hand wash using spot-free water
Thorough cleaning of wheels, wheel wells, tires, and gas cap area
Remove bug splatters from exterior surfaces
Remove bonded environmental fallout using a clay bar
Chemically remove tar and road grime
Application of high-grade 1-year ceramic coating'
FROM svc s WHERE s.slug = 'ceramic-coating'
UNION ALL
SELECT s.id, 1,
       '3 Year Ceramic Coating',
       '3 Year ceramic coating',
       360,
       1100, 1100, 1200, 1300,
       NULL, NULL, NULL,
       7,
       'Benefits of Ceramic Coating:
Protects your vehicle''s paint from UV damage and oxidation
Maintains long-term paint condition and resale value
Creates a hydrophobic barrier that repels water & contaminants
Enhances gloss, depth, and color clarity for a rich, polished finish
Reduces maintenance time & makes cleaning effortless
Pre-wash and 100% hand wash using spot-free water
Thorough cleaning of wheels, wheel wells, tires, and gas cap area
Remove bug splatters from exterior surfaces
Remove bonded environmental fallout using a clay bar
Chemically remove tar and road grime
1-Step Paint Correction – removes 50–60% of light swirls
Application of high-grade 3-year ceramic coating'
FROM svc s WHERE s.slug = 'ceramic-coating'
UNION ALL
SELECT s.id, 2,
       '5 Year Ceramic Coating',
       '5 Year ceramic coating',
       540,
       1200, 1200, 1300, 1400,
       NULL, NULL, NULL,
       10,
       'Benefits of Ceramic Coating:
Protects your vehicle''s paint from UV damage and oxidation
Maintains long-term paint condition and resale value
Creates a hydrophobic barrier that repels water & contaminants
Enhances gloss, depth, and color clarity for a rich, polished finish
Reduces maintenance time & makes cleaning effortless
Pre-wash and 100% hand wash using spot-free water
Thorough cleaning of wheels, wheel wells, tires, and gas cap area
Remove bug splatters from exterior surfaces
Remove bonded environmental fallout using a clay bar
Chemically remove tar and road grime
2-Step Paint Correction – removes 60–80% of light swirls
Application of high-grade 5-year ceramic coating'
FROM svc s WHERE s.slug = 'ceramic-coating'

UNION ALL
-- Paint Correction (no booking after 10AM); UI shows "Starting from $600" / "$800" — tiered DB prices for cart/API
SELECT s.id, 0,
       '1 Step paint correction',
       '1 Step paint correction',
       360,
       600, 600, 700, 800,
       NULL, NULL, NULL,
       7,
       'Pre-wash and 100% hand wash using spot-free water
Thorough cleaning of wheels, wheel wells, tires, and gas cap area
Remove bug splatters from exterior surfaces
Remove bonded environmental fallout using a clay bar
Chemically remove tar and road grime
1 step paint correction - remove 50 - 60% of light swirls
Upgrade Option:
Our professional 1-Step Paint Correction removes up to 80% of visible scratches and defects, dramatically improving gloss, clarity and overall paint appearance.'
FROM svc s WHERE s.slug = 'paint-correction'
UNION ALL
SELECT s.id, 1,
       '2 Step paint correction',
       '2 Step paint correction',
       570,
       800, 800, 1000, 1200,
       NULL, NULL, NULL,
       10,
       'Pre-wash and 100% hand wash using spot-free water
Cleaning of wheels, wheel wells, tires and gas cap area, including:
Remove bug splatters from exterior surfaces
Remove bonded environmental fallout using a clay bar
Chemically remove tar and road grime
2 Step Paint Correction (remove 60-80% of light swirls)
With our 2 step paint correction service, you can get up to 80% of scratches and defects removed based on original condition. The process requires more time and energy than the 1 step enhancement polish, but benefits from a much higher level of scratch, defect and swirl removal.'
FROM svc s WHERE s.slug = 'paint-correction'

UNION ALL
-- Monthly Maintenance (no booking after 4PM; Biweekly hidden in UI for now)
SELECT s.id, 0,
       'Biweekly',
       'Biweekly maintenance',
       150,
       350, 350, 370, 395,
       NULL, NULL, NULL,
       2,
       'Interior Maintenance
Complete vacuum of carpets and trunk area
Wipe-down of vinyl or rubber floor mats
Vacuum cloth seats
Leather seat wipe-down and conditioning
Dashboard cleaning with UV protection
Cleaning of console, cup holders, vents, and tight areas
Wipe-down of interior trim and plastics
Door jamb cleaning
Interior and exterior glass cleaned streak-free
Protective treatment applied to leather and vinyl surfaces
Exterior Maintenance
Pre-rinse using spot-free water
Complete hand wash using spot-free water
Wheels and tires cleaned by hand
Trim dressing applied
No-sling tire shine
Paint sealant application to maintain gloss and protection'
FROM svc s WHERE s.slug = 'monthly-maintenance'
UNION ALL
SELECT s.id, 1,
       'Monthly',
       '1 month maintenance',
       165,
       150, 150, 175, 190,
       NULL, NULL, NULL,
       3,
       'Interior Maintenance
Full vacuum of carpets and trunk
Light wipe-down of floor mats (vinyl/rubber)
Vacuum cloth seats
Wipe down leather seats
Leather seat conditioning treatment
Clean dashboard and apply UV protection
Detailed wipe-down of trim, panels, console, vents, and cup holders
Door jamb light wipe down
Interior and exterior glass cleaning
Protective treatment applied to leather and vinyl surfaces
Exterior Maintenance
Pre-rinse using spot-free water
Complete hand wash using spot-free water
Wheels and tires cleaned by hand
No-sling tire shine
Paint sealant applied to maintain protection and gloss
Important Notes: The vehicle must first get full detailing by our team and be maintained on a 4-week schedule to qualify for maintenance pricing. Excessive buildup, heavy pet hair, or severe staining may require upgrade to a higher-level detail.'
FROM svc s WHERE s.slug = 'monthly-maintenance'

UNION ALL
-- Fleet Detailing
SELECT s.id, 0,
       'Wash & Spray Wax',
       'Wash and spray wax. Pricing per foot.',
       60,
       15, 15, 15, 15,
       15, 15, 15,
       1,
       'Wash and spray wax'
FROM svc s WHERE s.slug = 'fleet-detailing'
UNION ALL
SELECT s.id, 1,
       'Wash & Hand Wax',
       'Wash and hand wax. Pricing per foot.',
       120,
       35, 35, 35, 35,
       35, 35, 35,
       2,
       'Wash and hand wax'
FROM svc s WHERE s.slug = 'fleet-detailing';

COMMIT;
